### ISSUE TITLE
idb-polyfill not in npm registry

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-range#1]
Hi,

https://www.npmjs.com/package/idb-polyfill does not exist and it is listed as a `package.json` dependency. Could you either publish that polyfill library to npm or remove it as a dependency and test requirement?

**Comment by brettz9** [comment]
Btw, although I didn't end up needing to include your repo given that I needed to delay the generation of the IDBKeyRange, your code was still helpful. Added now to my fork of db.js ([docs](https://github.com/brettz9/db.js#user-content-querying-using-indexes)). The filed issue here though is still valid.

**Comment by alekseykulikov** [comment]
fixed with https://github.com/treojs/idb-range/commit/967836b463b870611471dbcdcfefca2c0e04d093
