### ISSUE TITLE
babel compilation on latest version is producing weird module exports

### ISSUE THREAD

**Issue by rdy** [treojs/idb-range#2]
It looks like version 3.1.0 does not export the module correctly, probably needs `transform-es2015-modules-systemjs`.

When requiring the range the function exported is called default instead of it being the function being module.exports like it was in version 3.0.0. You can see the difference when you look at the module output when comparing the two versions of the npm module.

Right now we're locking down to the older version but you should change the npm scripts to include the babel plugin.

**Comment by alekseykulikov** [comment]
Thanks for bug report. Just released 3.1.1 with a fix.
Seems that with babel@6 `export default` does not equal `module.exports =`... need to discover
